<?php

namespace STC\BannerBundle\Repository;

use STC\BannerBundle\Entity\Banner;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
	public function findEnabledByType($position)
	{  
		$query = $this->createQueryBuilder('b')
		->leftJoin('b.banner_type', 'bt')
		->andWhere('bt.position =:position')
		 ->andWhere('b.enabled =:enabled')
		->andWhere('b.status =:status')
		->setParameter('position', $position)
		->setParameter('enabled', Banner::ENABLED_YES)
		->setParameter('status', Banner::STATUS_ONLINE);
		
		return $query->getQuery()->getResult();
	}
}
