<?php

namespace STC\BannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BannerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerTypeRepository extends EntityRepository
{
}
