<?php

namespace STC\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findEvent()
    {
        $query = $this->createQueryBuilder('a')
            ->andWhere('a.enabled =:enabled')
            ->setParameter('enabled', true)
            ->orderBy('a.position', 'DESC');
        return $query->getQuery()->getResult();
    }
}
