<?php

namespace STC\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpeakeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakeurRepository extends EntityRepository
{
}
